#plant management service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend5
  labels:
    app: backend5
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend5
  template:
    metadata:
      labels:
        app: backend5
    spec:
      containers:
      - name: backend5
        image: backend5:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8007