import os

# os.system("minikube addons enable ingress")
# os.system("minikube addons enable ingress-dns")
# os.system("kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml")
os.system("kubectl apply -f coredns-config.yaml")
# os.system("kubectl apply -f coredns-deployment.yaml")
# os.system("kubectl apply -f kafka-deployment.yaml")
# os.system("kubectl wait --for=condition=ready pod/kafka-deployment")
# os.system("kubectl apply -f kafka-service.yaml")
# os.system("kubectl wait --for=condition=ready pod/kafka-service")
os.system("analysisService-deployment.yaml")
os.system("analysisService-service.yaml")
os.system("authenticationService-deployment.yaml")
os.system("authenticationService-service.yaml")
os.system("dataQueringService-deployment.yaml")
os.system("dataQueringService-service.yaml")
os.system("oldDataRemoverService-deployment.yaml")
os.system("oldDataRemoverService-service.yaml")
os.system("plantManagementService-deployment.yaml")
os.system("plantManagementService-service.yaml")
os.system("schedulerService-deployment.yaml")
os.system("schedulerService-service.yaml")
os.system("sensorsService-deployment.yaml")
os.system("sensorsService-service.yaml")
os.system("weatherApiService-deployment.yaml")
os.system("weatherApiService-service.yaml")
os.system("kubectl apply -f ingress.yaml")
