import os

# os.system("minikube addons enable ingress")
# os.system("minikube addons enable ingress-dns")
# os.system("kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml")
os.system("kubectl apply -f coredns-config.yaml")
# os.system("kubectl apply -f coredns-deployment.yaml")
# os.system("kubectl apply -f kafka-deployment.yaml")
# os.system("kubectl wait --for=condition=ready pod/kafka-deployment")
# os.system("kubectl apply -f kafka-service.yaml")
# os.system("kubectl wait --for=condition=ready pod/kafka-service")
os.system("kubectl apply -f fastapi-app1-deployment.yaml")
os.system("kubectl apply -f fastapi-app1-service.yaml")
os.system("kubectl apply -f fastapi-app2-deployment.yaml")
os.system("kubectl apply -f fastapi-app2-service.yaml")
os.system("kubectl apply -f fastapi-app3-deployment.yaml")
os.system("kubectl apply -f fastapi-app3-service.yaml")
os.system("kubectl apply -f fastapi-app4-deployment.yaml")
os.system("kubectl apply -f fastapi-app4-service.yaml")
os.system("kubectl apply -f fastapi-app5-deployment.yaml")
os.system("kubectl apply -f fastapi-app5-service.yaml")
os.system("kubectl apply -f fastapi-app6-deployment.yaml")
os.system("kubectl apply -f fastapi-app6-service.yaml")
os.system("kubectl apply -f fastapi-app7-deployment.yaml")
os.system("kubectl apply -f fastapi-app7-service.yaml")
os.system("kubectl apply -f fastapi-app8-deployment.yaml")
os.system("kubectl apply -f fastapi-app8-service.yaml")
os.system("kubectl apply -f ingress.yaml")